<a href="https://colab.research.google.com/github/himalayahall/cuny-bridge-math/blob/main/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

In [71]:
A = np.matrix('1, 2; 3, 4')
print(A)
B = np.matrix('1, 2; 3, 4')
print(B)
C = np.matrix('1, 2, 3; 1, 2, 3')
print(C)
C

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2 3]
 [1 2 3]]


matrix([[1, 2, 3],
        [1, 2, 3]])

In [28]:
np.add(A, B)

matrix([[2, 4],
        [6, 8]])

In [29]:
np.subtract(A, B)

matrix([[0, 0],
        [0, 0]])

In [30]:
np.add(A, B) == np.add(B, A)

matrix([[ True,  True],
        [ True,  True]])

In [31]:
np.add(A, 0)

matrix([[1, 2],
        [3, 4]])

In [32]:
A+0

matrix([[1, 2],
        [3, 4]])

In [33]:
A@B

matrix([[ 7, 10],
        [15, 22]])

In [35]:
A@C

matrix([[ 3,  6,  9],
        [ 7, 14, 21]])

In [44]:
A_inv = np.linalg.pinv(A)
A_inv

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [45]:
A@A_inv

matrix([[ 1.00000000e+00, -6.66133815e-16],
        [ 1.77635684e-15,  1.00000000e+00]])

In [48]:
a = np.array([[5,2], [-3, 0]])
b = np.array([2, 2])
x = np.linalg.solve(a, b)
x

array([-0.66666667,  2.66666667])

In [54]:
A = np.matrix('1, 1; 4, 1')
print(A)

[[1 4]
 [4 1]]


In [56]:
Ident = np.identity(2)
Ident

array([[1., 0.],
       [0., 1.]])

In [60]:
from sympy import Symbol, solve
l = Symbol('l')
p = (1 - l)*(1 - l) - (4 * 1)
solve(p)

[-1, 3]

In [162]:
B = np.array([[1, 2],[3,4]])
B
C = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
def getMatrixMinor(m, col):
    return [row[:col] + row[col+1:] for row in (m[1:])]

def getMatrixDeternminant(m):

  # 1X1 matrix
  if (len(m) == 1):
    return A[0]

  # 2x2 matrix
  if len(m) == 2:
      return m[0][0]*m[1][1]-m[0][1]*m[1][0]

  determinant = 0.0
  for col in range(len(m)):

      # focus value - column of first row
      fc = m[0][col]

      # multiplication sign
      sign = (-1)**col

      # get minor matrix for column
      mm = getMatrixMinor(m, col)

      # compute minor matrix determinant
      mm_det = getMatrixDeternminant(mm)

      determinant += sign * fc * mm_det
  
  return determinant


A = [[-2, 2,-3],[-1,1,3],[2,0,-1]] 
B = [[4, -3, 5],[1, 0, 3],[-1, 5, 2]]
C = [[1, 2],[3,4]]

print('Matrix: {0} np.linalg.det: {1}, My det: {2}'.format(A, np.linalg.det(A), getMatrixDeternminant(A)))
print('Matrix: {0}, np.linalg.det: {1}, My det: {2}'.format(B, np.linalg.det(B), getMatrixDeternminant(B)))
print('Matrix: {0}, np.linalg.det: {1}, My det: {2}'.format(C, np.linalg.det(C), getMatrixDeternminant(C)))


Matrix: [[-2, 2, -3], [-1, 1, 3], [2, 0, -1]] np.linalg.det: 17.999999999999996, My det: 18.0
Matrix: [[4, -3, 5], [1, 0, 3], [-1, 5, 2]], np.linalg.det: -20.000000000000007, My det: -20.0
Matrix: [[1, 2], [3, 4]], np.linalg.det: -2.0000000000000004, My det: -2
