<a href="https://colab.research.google.com/github/himalayahall/cuny-bridge-math/blob/main/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.matrix('1, 2; 3, 4')
print(A)
B = np.matrix('1, 2; 3, 4')
print(B)
C = np.matrix('1, 2, 3; 1, 2, 3')
print(C)
C

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2 3]
 [1 2 3]]


matrix([[1, 2, 3],
        [1, 2, 3]])

In [ ]:
np.add(A, B)

matrix([[2, 4],
        [6, 8]])

In [ ]:
np.subtract(A, B)

matrix([[0, 0],
        [0, 0]])

In [ ]:
np.add(A, B) == np.add(B, A)

matrix([[ True,  True],
        [ True,  True]])

In [ ]:
np.add(A, 0)

matrix([[1, 2],
        [3, 4]])

In [ ]:
A+0

matrix([[1, 2],
        [3, 4]])

In [ ]:
A@B

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
A@C

matrix([[ 3,  6,  9],
        [ 7, 14, 21]])

In [ ]:
A_inv = np.linalg.pinv(A)
A_inv

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
A@A_inv

matrix([[ 1.00000000e+00, -6.66133815e-16],
        [ 1.77635684e-15,  1.00000000e+00]])

In [ ]:
a = np.array([[5,2], [-3, 0]])
b = np.array([2, 2])
x = np.linalg.solve(a, b)
x

array([-0.66666667,  2.66666667])

In [ ]:
A = np.matrix('1, 1; 4, 1')
print(A)

[[1 4]
 [4 1]]


In [ ]:
Ident = np.identity(2)
Ident

array([[1., 0.],
       [0., 1.]])

In [ ]:
from sympy import Symbol, solve
l = Symbol('l')
p = (1 - l)*(1 - l) - (4 * 1)
solve(p)

[-1, 3]

In [ ]:
B = np.array([[1, 2],[3,4]])
B
C = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np

def getMatrixMinor(m, col):
    return [row[:col] + row[col+1:] for row in (m[1:])]

def getMatrixDeternminant(m):
  '''
    Compute determinant.
    Params:
    m : square matrix
    Output:
    Determinant
  '''
  # 1X1 matrix
  if (len(m) == 1):
    return A[0]

  # 2x2 matrix
  if len(m) == 2:
      return m[0][0]*m[1][1]-m[0][1]*m[1][0]

  determinant = 0.0
  for col in range(len(m)):

      # focus value - column of first row
      fc = m[0][col]

      # multiplication sign
      sign = (-1)**col

      # get minor matrix for column
      mm = getMatrixMinor(m, col)

      # compute minor matrix determinant
      mm_det = getMatrixDeternminant(mm)

      determinant += sign * fc * mm_det
  
  return determinant


A = [[-2, 2,-3],[-1,1,3],[2,0,-1]] 
B = [[4, -3, 5],[1, 0, 3],[-1, 5, 2]]
C = [[1, 2],[3,4]]

print('Matrix: {0} np.linalg.det: {1}, My det: {2}'.format(A, np.linalg.det(A), getMatrixDeternminant(A)))
print('Matrix: {0}, np.linalg.det: {1}, My det: {2}'.format(B, np.linalg.det(B), getMatrixDeternminant(B)))
print('Matrix: {0}, np.linalg.det: {1}, My det: {2}'.format(C, np.linalg.det(C), getMatrixDeternminant(C)))


Matrix: [[-2, 2, -3], [-1, 1, 3], [2, 0, -1]] np.linalg.det: 17.999999999999996, My det: 18.0
Matrix: [[4, -3, 5], [1, 0, 3], [-1, 5, 2]], np.linalg.det: -20.000000000000007, My det: -20.0
Matrix: [[1, 2], [3, 4]], np.linalg.det: -2.0000000000000004, My det: -2


In [ ]:
# Ax = Lx
# Ax - Lx = 0
# Ax - LIx = 0
# (A - LI)x = 0
# x cannot be the 0 vector
# Assume (A - LI) is invertible, multiply both sides by the inverse
# (A - LI)'(A - LI)x = (A - LI)'0
# x = (A - LI)'0 = 0
# but that is not allowed, so (A - LI) cannot be invertible. That implies the determinant of (A - LI) must be 0
# |A - LI| = 0, is called the characteristic equation, solutions to this equation are the Eigenvalues
#
# Example:
# A = [[1, 1], [4, 1]], I = [[1, 0], [0, 1]]
#
# A - LI = [1, 1], [4, 1]] - L [[1, 0], [0, 1]] = [[1, 1], [4, 1]] - [L, 0], [0, L)] = [[1 - L, 1], [4, 1 - L]]
#
# Determinant of this must be 0
# (1 - L)(1 - L) - 1 * 4 = (1 - L)(1 - L) - 4 = 1 - L - L + L**2 - 4 = L**2 - 2L -3 = 0
#
# Factoring: (L - 3)(L + 1) = 0, which has two solutions: L = 3, L = -1. These are. the eigenvalues
#
from sympy import Symbol, pprint, solve

L = Symbol('lambda')

exp0 = L**2 - 2 * L - 3
pprint(exp0)
print(solve(exp0))

exp1 = (1 - L)*(1 - L) - 1 * 4
pprint(exp1)
print(solve(exp1))


 2          
λ  - 2⋅λ - 3
[-1, 3]
       2    
(1 - λ)  - 4
[-1, 3]


In [3]:
from sympy import Symbol, pprint, solve
import numpy as np

def get_eigenvalues_for_2By2(M):
  '''
    Get engenvalues for any 2x2 matrix
  '''
  if (len(M[0]) == len(M[1]) and len(M[0]) == 2):
    L = Symbol('lambda')
    exp = (M[0][0] - L) * (M[1][1] - L) - (M[0][1] * M[1][0])
    #print(exp)
    return solve(exp)

def get_eigenvalues_for_3By3(M):
  '''
    Get engenvalues for any 3x3 matrix
  '''
  if (len(M[0]) == len(M[1]) and len(M[0]) == 3):
    L = Symbol('lambda')
    a00 = (M[0][0] - L)
    a01 = M[0][1]
    a02 = M[0][2]

    a10 = M[1][0]
    a11 = (M[1][1] - L)
    a12 = M[1][2]

    a20 = M[2][0]
    a21 = M[2][1]
    a22 = (M[2][2] - L)

    exp1 = a00 * (a11 * a22 - a12 * a21)
    exp2 = a01 * (a10 * a22 - a12 * a20)
    exp3 = a02 * (a10 * a21 - a11 * a20)

    return solve(exp1 - exp2 + exp3)

C = [[1, 1],[4, 1]]
solC = get_eigenvalues_for_2By2(C)
print('My Eigenvalue: {0}, np.linalg.eigvals: {1}'.format(solC, np.linalg.eigvals(C)))

D = [[-2, -4, 2], [-2, 1, 2], [4, 2, 5]]
solD = get_eigenvalues_for_3By3(D)
print('My Eigenvalue: {0}, np.linalg.eigvals: {1}'.format(solD, np.linalg.eigvals(D)))

My Eigenvalue: [-1, 3], np.linalg.eigvals: [ 3. -1.]
My Eigenvalue: [-5, 3, 6], np.linalg.eigvals: [-5.  3.  6.]


In [53]:
from sympy import Symbol, pprint, solve, Matrix, eye, diag

def get_eigenvalues(in_arr):
  '''
    Solve for Eigenvalues of any NxM matrix.
  '''

  # create matrix, A
  A = Matrix(in_arr)

  # create same size identity matrix, I
  I = eye(len(in_arr[0]))

  # put lambda on diagonal of identity matrix, LI
  L = Symbol('lambda') 
  LI = L * I
  #print(LI)

  # A - LI
  A_LI = A - LI

  # compute |A - LI|
  det_A_LI = A_LI.det()
  #print(det_A_LI)

  # solve for |A - LI| = 0
  soln = solve(det_A_LI)
  #print(soln)

  return soln

A = [[1, 1],[4, 1]]
solA = get_eigenvalues(A)
print('Matrix: {0}, My Eigenvalue: {1}, np.linalg.eigvals: {2}'.format(A, solA, np.linalg.eigvals(A)))

B = [[-2, -4, 2], [-2, 1, 2], [4, 2, 5]]
solB = get_eigenvalues(B)
print('Matrix: {0}, My Eigenvalue: {1}, np.linalg.eigvals: {2}'.format(B, solB, np.linalg.eigvals(B)))

C = [[-2, 0, 0, 0], [0, 4, 0, 0], [0, 0, 3, 0], [0, 0, 3, 4]]
solC = get_eigenvalues(C)
print('Matrix: {0}, My Eigenvalue: {1}, np.linalg.eigvals: {2}'.format(C, solC, np.linalg.eigvals(C)))


Matrix: [[1, 1], [4, 1]], My Eigenvalue: [-1, 3], np.linalg.eigvals: [ 3. -1.]
Matrix: [[-2, -4, 2], [-2, 1, 2], [4, 2, 5]], My Eigenvalue: [-5, 3, 6], np.linalg.eigvals: [-5.  3.  6.]
Matrix: [[-2, 0, 0, 0], [0, 4, 0, 0], [0, 0, 3, 0], [0, 0, 3, 4]], My Eigenvalue: [-2, 3, 4], np.linalg.eigvals: [-2.  4.  4.  3.]


In [ ]:
import numpy as np

def get_eigvec(M):
  '''
    Shortcut - using numpy eig to calculate eigenvectors
  '''
  return np.linalg.eig(M)[1]
 
def get_eigval(M):
  '''
    Shortcut - using numpy eig to cacculate eigenvectors
  '''
  return np.linalg.eig(M)[0]

C = [[1, 1],[4, 1]]
print('Eigval: {0}, Eigvec: {1}'.format(get_eigval(C), get_eigvec(C)))

Eigval: [ 3. -1.], Eigvec: [[ 0.4472136  -0.4472136 ]
 [ 0.89442719  0.89442719]]


In [ ]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

A = array([[1,2], [3,4],
                [5,6]],
               dtype=np.float32)
  
print('Original array =', A)
  
# Compute the factor by Singular Value 
# Decomposition
U, s, VT = svd(A, full_matrices=False)

# Print the result
print("\nFactor of the given array by Singular Value Decomposition:")
print("\nU=", U, "\n\ns=", s, "\n\nVT=", VT)


Original array = [[1. 2.]
 [3. 4.]
 [5. 6.]]

Factor of the given array by Singular Value Decomposition:

U= [[-0.22984788  0.8834613 ]
 [-0.5247448   0.24078177]
 [-0.819642   -0.40189567]] 

s= [9.525519   0.51430136] 

VT= [[-0.6196294 -0.7848945]
 [-0.7848945  0.6196294]]
